#!/usr/bin/env node
/**
 * Single registry of committed files that are *projected* from other files in
 * this repo.
 *
 * Every entry below is regenerated by `npm run generate:derived` and gated by
 * `npm run check:derived`. Keeping one list means a projection cannot be added
 * with a generator but no freshness gate — the failure mode that let
 * data/templates-snapshot.json and plugins/open-agreements/ drift on main.
 *
 * Adding a new derived artifact: add one entry here. Do not add a bespoke
 * generate:/check: pair to package.json without also registering it.
 *
 * SCOPE: fast, textual, byte-comparable projections only — not every generated
 * file in the repo. The ~108 tracked template.docx binaries under templates/
 * are also generated (generate_templates.mjs, generate_checklist_template.mjs,
 * generate_working_group_template.mjs,
 * generate_employment_templates_libreoffice.mjs) but deliberately stay out:
 * they need LibreOffice, are slow, and DOCX is a zip whose bytes are not stable
 * across runs, so a git-diff freshness gate would false-positive. They are
 * gated instead by template-preview-gate (check:template-previews,
 * check:docx-structure) and preview-freshness-gate, which check structure and
 * preview currency rather than byte-for-byte regeneration.
 *
 * Also not registered: generate_json_schemas.mjs and generate_concerto_types.mjs
 * write untracked build product (packages/contracts-workspace/schemas/,
 * site/schemas/, concerto/generated/), so there is nothing to drift.
 */
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** @type {{id: string, script: string, paths: string[], needsBuild?: boolean}[]} */
const artifacts = [
  {
    id: "readme",
    script: "scripts/generate_readme.mjs",
    paths: ["README.md", "docs/reference/catalog.md"],
    needsBuild: true,
  },
  {
    id: "llms",
    script: "scripts/generate_llms_txt.mjs",
    paths: ["llms.txt", "llms-full.txt"],
  },
  {
    id: "claude-plugin",
    script: "scripts/sync_claude_marketplace_plugin.mjs",
    paths: ["plugins/open-agreements"],
  },
  {
    id: "templates-snapshot",
    script: "scripts/export-templates-snapshot.mjs",
    paths: ["data/templates-snapshot.json"],
  },
];


const allPaths = artifacts.flatMap((artifact) => artifact.paths);

function run(command, args, label) {
  try {
    execFileSync(command, args, { cwd: repoRoot, stdio: "inherit" });
  } catch {
    // execFileSync rethrows the child's stack on top of ours, which buries the
    // generator's own error message. The child already printed it; just say
    // which step died and stop.
    console.error(`\nDerived-artifact step failed: ${label}`);
    process.exit(1);
  }
}

function gitStatus(paths) {
  return execFileSync("git", ["status", "--porcelain", "--", ...paths], {
    cwd: repoRoot,
    encoding: "utf8",
  }).trim();
}

function generate({ quiet = false } = {}) {
  if (artifacts.some((artifact) => artifact.needsBuild)) {
    if (!quiet) console.log("→ building (some generators import dist/)");
    run("npm", ["run", "build"], "npm run build");
  }
  for (const artifact of artifacts) {
    if (!quiet) console.log(`→ ${artifact.id}`);
    run("node", [artifact.script], artifact.id);
  }
}

function check() {
  // Refuse to run against a dirty registered path. Diffing porcelain before and
  // after regeneration looks like it would isolate new drift, but it cannot: an
  // already-modified file that regeneration modifies *further* keeps the exact
  // same porcelain line (" M path"), so the difference is empty and the check
  // reports "current" while the file is stale. Requiring a clean start is both
  // simpler and honest — CI always starts clean, so this only ever fires
  // locally, where the answer is to stash or commit first.
  const dirty = gitStatus(allPaths).split("\n").filter(Boolean);
  if (dirty.length > 0) {
    console.error("Cannot check: these derived paths have uncommitted changes.\n");
    for (const line of dirty) console.error(`  ${line}`);
    console.error("\nCommit or stash them first — a dirty start hides real drift.");
    process.exitCode = 1;
    return;
  }

  generate({ quiet: true });
  const drifted = gitStatus(allPaths).split("\n").filter(Boolean);

  if (drifted.length === 0) {
    console.log(`Derived artifacts are current (${artifacts.length} projections).`);
    return;
  }

  console.error("Derived artifacts are stale. Regenerate and commit them:\n");
  console.error("    npm run generate:derived\n");
  console.error("Stale paths:");
  for (const line of drifted) console.error(`  ${line}`);
  process.exitCode = 1;
}

const mode = process.argv[2] ?? "--generate";
if (mode === "--check") check();
else if (mode === "--generate") generate();
else {
  console.error(`Unknown argument: ${mode} (expected --generate or --check)`);
  process.exitCode = 2;
}
