#!/usr/bin/env node
/**
 * Single registry of committed files that are *projected* from other files in
 * this repo.
 *
 * Every entry below is regenerated by `npm run generate:derived` and gated by
 * `npm run check:derived`. Keeping one list means a projection cannot be added
 * with a generator but no freshness gate — the failure mode that let
 * data/templates-snapshot.json and plugins/open-agreements/ drift on main.
 *
 * Adding a new derived artifact: add one entry here. Do not add a bespoke
 * generate:/check: pair to package.json without also registering it.
 *
 * Deliberately NOT registered: generators that rewrite DOCX binaries or render
 * PNG previews (generate:templates, generate:template-previews). Those need
 * LibreOffice, are slow, and are gated separately by template-preview-gate.
 */
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** @type {{id: string, script: string, paths: string[], needsBuild?: boolean}[]} */
const artifacts = [
  {
    id: "readme",
    script: "scripts/generate_readme.mjs",
    paths: ["README.md", "docs/reference/catalog.md"],
    needsBuild: true,
  },
  {
    id: "llms",
    script: "scripts/generate_llms_txt.mjs",
    paths: ["llms.txt", "llms-full.txt"],
  },
  {
    id: "claude-plugin",
    script: "scripts/sync_claude_marketplace_plugin.mjs",
    paths: ["plugins/open-agreements"],
  },
  {
    id: "templates-snapshot",
    script: "scripts/export-templates-snapshot.mjs",
    paths: ["data/templates-snapshot.json"],
  },
];

// generate:schemas and generate:concerto are intentionally absent: their output
// is untracked build product, not committed files, so there is nothing to drift.

const allPaths = artifacts.flatMap((artifact) => artifact.paths);

function run(command, args, label) {
  try {
    execFileSync(command, args, { cwd: repoRoot, stdio: "inherit" });
  } catch {
    // execFileSync rethrows the child's stack on top of ours, which buries the
    // generator's own error message. The child already printed it; just say
    // which step died and stop.
    console.error(`\nDerived-artifact step failed: ${label}`);
    process.exit(1);
  }
}

function gitStatus(paths) {
  return execFileSync("git", ["status", "--porcelain", "--", ...paths], {
    cwd: repoRoot,
    encoding: "utf8",
  }).trim();
}

function generate({ quiet = false } = {}) {
  if (artifacts.some((artifact) => artifact.needsBuild)) {
    if (!quiet) console.log("→ building (some generators import dist/)");
    run("npm", ["run", "build"], "npm run build");
  }
  for (const artifact of artifacts) {
    if (!quiet) console.log(`→ ${artifact.id}`);
    run("node", [artifact.script], artifact.id);
  }
}

function check() {
  // Anything already dirty is pre-existing local work, not drift this run
  // introduced. Record it so we only report what regeneration actually changed.
  const before = new Set(gitStatus(allPaths).split("\n").filter(Boolean));
  generate({ quiet: true });
  const after = gitStatus(allPaths).split("\n").filter(Boolean);
  const drifted = after.filter((line) => !before.has(line));

  if (drifted.length === 0) {
    console.log(`Derived artifacts are current (${artifacts.length} projections).`);
    return;
  }

  console.error("Derived artifacts are stale. Regenerate and commit them:\n");
  console.error("    npm run generate:derived\n");
  console.error("Stale paths:");
  for (const line of drifted) console.error(`  ${line}`);
  process.exitCode = 1;
}

const mode = process.argv[2] ?? "--generate";
if (mode === "--check") check();
else if (mode === "--generate") generate();
else {
  console.error(`Unknown argument: ${mode} (expected --generate or --check)`);
  process.exitCode = 2;
}
