#!/usr/bin/env node

/**
 * CI lint: enforce that `metadata.legal-context.yaml` (if present) only declares
 * field names that exist in the sibling `metadata.yaml`, and only sets keys
 * that legal-context is allowed to own.
 *
 * The sidecar is generated by legal-context's sync_open_agreements.py; this
 * lint catches:
 *
 *   1. A field renamed in metadata.yaml without regenerating the sidecar.
 *   2. A hand-edit to the sidecar introducing an unknown field name.
 *   3. A hand-edit to the sidecar setting a key outside the allowed owned set.
 *
 * The shape of ownership:
 *   metadata.yaml              hand-authored (open-agreements-owned)
 *   metadata.legal-context.yaml generated     (legal-context-owned)
 *
 * Field-name alignment is a duplication-as-feature — legal-context has to know
 * field names to fill them anyway, so surfacing the duplication in two files
 * lets us lint it.
 *
 * See open-agreements/README.md § "Two-sidecar ownership model" and
 * legal-context docs/restrictive-covenant-tracker-vision.md.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const TEMPLATES_DIR = resolve(ROOT, "content", "templates");

const ALLOWED_OWNED_KEYS = new Set([
  "default",
  "default_value_rationale",
  "options",
  "display",
]);

function listTemplateIds() {
  return readdirSync(TEMPLATES_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

function loadYaml(path) {
  const raw = readFileSync(path, "utf8");
  const parsed = yaml.load(raw);
  return parsed && typeof parsed === "object" ? parsed : null;
}

function collectFieldNames(metadataFields) {
  const names = new Set();
  if (!Array.isArray(metadataFields)) return names;
  for (const f of metadataFields) {
    if (f && typeof f.name === "string") names.add(f.name);
  }
  return names;
}

function checkTemplate(templateId) {
  const dir = resolve(TEMPLATES_DIR, templateId);
  const sidecarPath = resolve(dir, "metadata.legal-context.yaml");
  if (!existsSync(sidecarPath)) {
    return { templateId, hasSidecar: false, errors: [] };
  }

  const errors = [];
  const metadataPath = resolve(dir, "metadata.yaml");
  if (!existsSync(metadataPath)) {
    errors.push("metadata.legal-context.yaml present but no sibling metadata.yaml");
    return { templateId, hasSidecar: true, errors };
  }

  const metadata = loadYaml(metadataPath);
  const sidecar = loadYaml(sidecarPath);
  if (!sidecar) {
    errors.push("metadata.legal-context.yaml is not a YAML mapping");
    return { templateId, hasSidecar: true, errors };
  }

  const sidecarTopKeys = Object.keys(sidecar);
  for (const key of sidecarTopKeys) {
    if (key !== "fields") {
      errors.push(
        `metadata.legal-context.yaml: top-level key "${key}" is not allowed. Only "fields" is permitted.`
      );
    }
  }

  if (!Array.isArray(sidecar.fields)) {
    errors.push("metadata.legal-context.yaml: fields must be an array");
    return { templateId, hasSidecar: true, errors };
  }

  const declaredFieldNames = collectFieldNames(metadata?.fields);

  for (const [idx, entry] of sidecar.fields.entries()) {
    if (!entry || typeof entry !== "object") {
      errors.push(`metadata.legal-context.yaml: fields[${idx}] is not an object`);
      continue;
    }
    const name = entry.name;
    if (typeof name !== "string" || !name) {
      errors.push(`metadata.legal-context.yaml: fields[${idx}] missing "name"`);
      continue;
    }
    if (!declaredFieldNames.has(name)) {
      errors.push(
        `metadata.legal-context.yaml: fields[${idx}] "${name}" is not declared in metadata.yaml. ` +
        `Either the field was renamed/removed in metadata.yaml (regenerate the sidecar), ` +
        `or the sidecar was hand-edited to reference a nonexistent field.`
      );
    }
    for (const key of Object.keys(entry)) {
      if (key === "name") continue;
      if (!ALLOWED_OWNED_KEYS.has(key)) {
        errors.push(
          `metadata.legal-context.yaml: fields[${idx}] "${name}" sets "${key}", which is not in ` +
          `the legal-context-owned key set (${[...ALLOWED_OWNED_KEYS].join(", ")}).`
        );
      }
    }
  }

  return { templateId, hasSidecar: true, errors };
}

function main() {
  const templateIds = listTemplateIds();
  const results = templateIds.map(checkTemplate);

  const withSidecars = results.filter((r) => r.hasSidecar);
  const failing = withSidecars.filter((r) => r.errors.length > 0);

  if (withSidecars.length === 0) {
    console.log("No metadata.legal-context.yaml sidecars found; nothing to validate.");
    return 0;
  }

  console.log(`Validating ${withSidecars.length} template(s) with legal-context sidecars:`);
  for (const r of withSidecars) {
    if (r.errors.length === 0) {
      console.log(`  \u2713 ${r.templateId}`);
    } else {
      console.log(`  \u2717 ${r.templateId}`);
      for (const err of r.errors) {
        console.log(`      - ${err}`);
      }
    }
  }

  if (failing.length > 0) {
    console.error(
      `\nmetadata-sidecar lint failed for ${failing.length} template(s). ` +
      `See legal-context docs/restrictive-covenant-tracker-vision.md for the ownership model.`
    );
    return 1;
  }
  console.log("\nAll metadata.legal-context.yaml sidecars are aligned with their metadata.yaml.");
  return 0;
}

process.exit(main());
